/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.CtrlClientes;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelo.MdlCliente;


/**
 *
 * @author scorpion
 */
public class VstClientesAdm extends javax.swing.JInternalFrame {

    /**
     * Creates new form VstClientes
     */
    //lista a nivel global, 
    ArrayList<MdlCliente> listaclientes = new ArrayList();
    //objeto cliente 
    MdlCliente cliente = null;

    public VstClientesAdm() {
        initComponents();
        llenarTabla();
    }

    public void habilitar() {
        CtrlClientes ctrlcliente = new CtrlClientes();
        if (cliente == null) {
            JOptionPane.showMessageDialog(null, "No hay registro para recuperar");
        } else {
            ctrlcliente.recuperar(cliente);
            limpiarTabla();
            llenarTabla();            
        }
    }

    public void llenarObjeto() {
        for (int posicion = 0; posicion < listaclientes.size(); posicion++) {
            if (tblclientes.getSelectedRow() == posicion) {
                cliente = (MdlCliente) listaclientes.get(posicion);
            }
        }
    }

    public void llenarTabla() {
        limpiarTabla();
        CtrlClientes ctrlcliente = new CtrlClientes();
        listaclientes = ctrlcliente.listaClienteIna();
        for (int posicion = 0; posicion < listaclientes.size(); posicion++) {
            tblclientes.setValueAt(posicion + 1, posicion, 0);
            tblclientes.setValueAt(((MdlCliente) listaclientes.get(posicion)).getNombre() + " " + ((MdlCliente) listaclientes.get(posicion)).getApellido(), posicion, 1);
            tblclientes.setValueAt(((MdlCliente) listaclientes.get(posicion)).getNumeroDoc(), posicion, 2);
            tblclientes.setValueAt(((MdlCliente) listaclientes.get(posicion)).getTipoDocumento(), posicion, 3);
            tblclientes.setValueAt(((MdlCliente) listaclientes.get(posicion)).getFechaNacimiento(), posicion, 4);
            tblclientes.setValueAt(((MdlCliente) listaclientes.get(posicion)).getDireccion(), posicion, 5);
            tblclientes.setValueAt(((MdlCliente) listaclientes.get(posicion)).getTelefono(), posicion, 6);
            tblclientes.setValueAt(((MdlCliente) listaclientes.get(posicion)).getCelular(), posicion, 7);
            tblclientes.setValueAt(((MdlCliente) listaclientes.get(posicion)).getCorreo(), posicion, 8);
            tblclientes.setValueAt("Inactivo", posicion, 9);
        }
    }

    public void limpiarTabla() {
        for (int posicion = 0; posicion < 100; posicion++) {
            tblclientes.setValueAt("", posicion, 0);
            tblclientes.setValueAt("", posicion, 1);
            tblclientes.setValueAt("", posicion, 2);
            tblclientes.setValueAt("", posicion, 3);
            tblclientes.setValueAt("", posicion, 4);
            tblclientes.setValueAt("", posicion, 5);
            tblclientes.setValueAt("", posicion, 6);
            tblclientes.setValueAt("", posicion, 7);
            tblclientes.setValueAt("", posicion, 8);
            tblclientes.setValueAt("", posicion, 9);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgrestado = new javax.swing.ButtonGroup();
        pnlprincipal = new javax.swing.JPanel();
        lblidpersona = new javax.swing.JLabel();
        lblidcliente = new javax.swing.JLabel();
        btnactualizar = new javax.swing.JButton();
        pnldetalle = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblclientes = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Gestión de Clientes");

        pnlprincipal.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12))); // NOI18N

        btnactualizar.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        btnactualizar.setText("Habilitar");
        btnactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlprincipalLayout = new javax.swing.GroupLayout(pnlprincipal);
        pnlprincipal.setLayout(pnlprincipalLayout);
        pnlprincipalLayout.setHorizontalGroup(
            pnlprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlprincipalLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(lblidpersona, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(lblidcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105)
                .addComponent(btnactualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                .addGap(312, 312, 312))
        );
        pnlprincipalLayout.setVerticalGroup(
            pnlprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlprincipalLayout.createSequentialGroup()
                .addGroup(pnlprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblidcliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnactualizar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblidpersona, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnldetalle.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Detalle", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12))); // NOI18N

        tblclientes = new javax.swing.JTable(){
            public boolean isCellEditable(int fila,int col){
                return false;
            }
        };
        tblclientes.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        tblclientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "#", "Nombre", "Numero Documento", "Tipo Documento", "Fecha Nacimiento", "Dirección", "Teléfono", "Celular", "Correo", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblclientes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblclientes.setFocusable(false);
        tblclientes.setRowMargin(4);
        tblclientes.getTableHeader().setReorderingAllowed(false);
        tblclientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblclientesMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblclientes);
        if (tblclientes.getColumnModel().getColumnCount() > 0) {
            tblclientes.getColumnModel().getColumn(0).setMinWidth(30);
            tblclientes.getColumnModel().getColumn(0).setPreferredWidth(50);
            tblclientes.getColumnModel().getColumn(0).setMaxWidth(50);
            tblclientes.getColumnModel().getColumn(1).setMinWidth(100);
            tblclientes.getColumnModel().getColumn(1).setPreferredWidth(300);
            tblclientes.getColumnModel().getColumn(1).setMaxWidth(300);
            tblclientes.getColumnModel().getColumn(2).setMinWidth(70);
            tblclientes.getColumnModel().getColumn(2).setPreferredWidth(150);
            tblclientes.getColumnModel().getColumn(2).setMaxWidth(150);
            tblclientes.getColumnModel().getColumn(3).setMinWidth(70);
            tblclientes.getColumnModel().getColumn(3).setPreferredWidth(150);
            tblclientes.getColumnModel().getColumn(3).setMaxWidth(150);
            tblclientes.getColumnModel().getColumn(4).setMinWidth(70);
            tblclientes.getColumnModel().getColumn(4).setPreferredWidth(150);
            tblclientes.getColumnModel().getColumn(4).setMaxWidth(150);
            tblclientes.getColumnModel().getColumn(5).setMinWidth(100);
            tblclientes.getColumnModel().getColumn(5).setPreferredWidth(200);
            tblclientes.getColumnModel().getColumn(5).setMaxWidth(200);
            tblclientes.getColumnModel().getColumn(6).setMinWidth(50);
            tblclientes.getColumnModel().getColumn(6).setPreferredWidth(100);
            tblclientes.getColumnModel().getColumn(6).setMaxWidth(100);
            tblclientes.getColumnModel().getColumn(7).setMinWidth(50);
            tblclientes.getColumnModel().getColumn(7).setPreferredWidth(100);
            tblclientes.getColumnModel().getColumn(7).setMaxWidth(100);
            tblclientes.getColumnModel().getColumn(8).setMinWidth(100);
            tblclientes.getColumnModel().getColumn(8).setPreferredWidth(250);
            tblclientes.getColumnModel().getColumn(8).setMaxWidth(250);
            tblclientes.getColumnModel().getColumn(9).setMinWidth(50);
            tblclientes.getColumnModel().getColumn(9).setPreferredWidth(100);
            tblclientes.getColumnModel().getColumn(9).setMaxWidth(100);
        }

        javax.swing.GroupLayout pnldetalleLayout = new javax.swing.GroupLayout(pnldetalle);
        pnldetalle.setLayout(pnldetalleLayout);
        pnldetalleLayout.setHorizontalGroup(
            pnldetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnldetalleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5)
                .addContainerGap())
        );
        pnldetalleLayout.setVerticalGroup(
            pnldetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnldetalleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlprincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnldetalle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlprincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnldetalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarActionPerformed
        // TODO add your handling code here:
        habilitar();
    }//GEN-LAST:event_btnactualizarActionPerformed

    private void tblclientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblclientesMouseClicked
        // TODO add your handling code here:
        llenarObjeto();
    }//GEN-LAST:event_tblclientesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgrestado;
    public javax.swing.JButton btnactualizar;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblidcliente;
    private javax.swing.JLabel lblidpersona;
    private javax.swing.JPanel pnldetalle;
    private javax.swing.JPanel pnlprincipal;
    public javax.swing.JTable tblclientes;
    // End of variables declaration//GEN-END:variables
}
