/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author scorpion
 */
public class VstMenu extends javax.swing.JFrame {

    /**
     * Creates new form VstMenu
     */
    public VstMenu() {
        initComponents();
        datos();
    }

    public void datos() {
        setTitle("Página Principal de Ventas");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dpn_interno = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        men_empleados = new javax.swing.JMenu();
        ime_gestionempleados = new javax.swing.JMenuItem();
        men_clientes = new javax.swing.JMenu();
        ime_gestionclientes = new javax.swing.JMenuItem();
        ime_recuperarclientes = new javax.swing.JMenuItem();
        men_productos = new javax.swing.JMenu();
        ime_gestionproducto = new javax.swing.JMenuItem();
        men_compras = new javax.swing.JMenu();
        men_ventas = new javax.swing.JMenu();
        ime_factura = new javax.swing.JMenuItem();
        ime_consultafacturas = new javax.swing.JMenuItem();
        men_proveedores = new javax.swing.JMenu();
        ime_proveedores = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        men_empleados.setText("Empleados");

        ime_gestionempleados.setText("Gestionar Empleados");
        ime_gestionempleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ime_gestionempleadosActionPerformed(evt);
            }
        });
        men_empleados.add(ime_gestionempleados);

        jMenuBar1.add(men_empleados);

        men_clientes.setText("Clientes");

        ime_gestionclientes.setText("Gestión Clientes");
        ime_gestionclientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ime_gestionclientesActionPerformed(evt);
            }
        });
        men_clientes.add(ime_gestionclientes);

        ime_recuperarclientes.setText("Recuperar Clientes");
        ime_recuperarclientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ime_recuperarclientesActionPerformed(evt);
            }
        });
        men_clientes.add(ime_recuperarclientes);

        jMenuBar1.add(men_clientes);

        men_productos.setText("Productos");

        ime_gestionproducto.setText("Gestión de Productos");
        ime_gestionproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ime_gestionproductoActionPerformed(evt);
            }
        });
        men_productos.add(ime_gestionproducto);

        jMenuBar1.add(men_productos);

        men_compras.setText("Compras");
        jMenuBar1.add(men_compras);

        men_ventas.setText("Ventas");

        ime_factura.setText("Facturar");
        ime_factura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ime_facturaActionPerformed(evt);
            }
        });
        men_ventas.add(ime_factura);

        ime_consultafacturas.setText("Consulta de Facturas");
        ime_consultafacturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ime_consultafacturasActionPerformed(evt);
            }
        });
        men_ventas.add(ime_consultafacturas);

        jMenuBar1.add(men_ventas);

        men_proveedores.setText("Proveedores");

        ime_proveedores.setText("Gestión Proveedores");
        ime_proveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ime_proveedoresActionPerformed(evt);
            }
        });
        men_proveedores.add(ime_proveedores);

        jMenuBar1.add(men_proveedores);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpn_interno, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpn_interno, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ime_facturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ime_facturaActionPerformed
        // TODO add your handling code here:
        VstFactura ventana = new VstFactura();        
        dpn_interno.add(ventana);
        ventana.show();
    }//GEN-LAST:event_ime_facturaActionPerformed

    private void ime_gestionclientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ime_gestionclientesActionPerformed
        // TODO add your handling code here:
        VstClientes ventana = new VstClientes();        
        dpn_interno.add(ventana);
        ventana.show();
    }//GEN-LAST:event_ime_gestionclientesActionPerformed

    private void ime_proveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ime_proveedoresActionPerformed
        // TODO add your handling code here:
        VstProveedores ventana = new VstProveedores();        
        dpn_interno.add(ventana);
        ventana.show();
    }//GEN-LAST:event_ime_proveedoresActionPerformed

    private void ime_consultafacturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ime_consultafacturasActionPerformed
        // TODO add your handling code here:
        VstConsulFactur ventana = new VstConsulFactur();        
        dpn_interno.add(ventana);
        ventana.show();
    }//GEN-LAST:event_ime_consultafacturasActionPerformed

    private void ime_gestionempleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ime_gestionempleadosActionPerformed
        // TODO add your handling code here:
//        VstEmpleados ventana = new VstEmpleados();        
//        dpn_interno.add(ventana);
//        ventana.show();
    }//GEN-LAST:event_ime_gestionempleadosActionPerformed

    private void ime_gestionproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ime_gestionproductoActionPerformed
        // TODO add your handling code here:
        VstProductos ventana = new VstProductos();        
        dpn_interno.add(ventana);
        ventana.show();
    }//GEN-LAST:event_ime_gestionproductoActionPerformed

    private void ime_recuperarclientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ime_recuperarclientesActionPerformed
        // TODO add your handling code here:
        VstClientesAdm ventana = new VstClientesAdm();        
        dpn_interno.add(ventana);
        ventana.show();
    }//GEN-LAST:event_ime_recuperarclientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VstMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VstMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VstMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VstMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VstMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane dpn_interno;
    private javax.swing.JMenuItem ime_consultafacturas;
    private javax.swing.JMenuItem ime_factura;
    private javax.swing.JMenuItem ime_gestionclientes;
    private javax.swing.JMenuItem ime_gestionempleados;
    private javax.swing.JMenuItem ime_gestionproducto;
    private javax.swing.JMenuItem ime_proveedores;
    private javax.swing.JMenuItem ime_recuperarclientes;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu men_clientes;
    private javax.swing.JMenu men_compras;
    private javax.swing.JMenu men_empleados;
    private javax.swing.JMenu men_productos;
    private javax.swing.JMenu men_proveedores;
    private javax.swing.JMenu men_ventas;
    // End of variables declaration//GEN-END:variables
}
