/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author scorpion
 */
public class VstProductos extends javax.swing.JInternalFrame {

    /**
     * Creates new form VstProductos
     */
    public VstProductos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Label_Productos = new javax.swing.JLabel();
        Combo_TProducto = new javax.swing.JComboBox<>();
        Label_Color = new javax.swing.JLabel();
        Combo_Color = new javax.swing.JComboBox<>();
        Label_Tproducto = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Label_Género = new javax.swing.JLabel();
        Radio_Masculino = new javax.swing.JRadioButton();
        Radio_Femenino = new javax.swing.JRadioButton();
        Label_Tono = new javax.swing.JLabel();
        Combo_Tono = new javax.swing.JComboBox<>();
        Label_Producto = new javax.swing.JLabel();
        Combo_Producto = new javax.swing.JComboBox<>();
        Label_Cantidad = new javax.swing.JLabel();
        Text_Cantidad = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        Text_Peso = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        Label_Peso = new javax.swing.JLabel();
        Combo_Marca = new javax.swing.JComboBox<>();
        Label_Marca = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Gestión Productos");

        Label_Productos.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        Label_Productos.setForeground(new java.awt.Color(0, 0, 0));
        Label_Productos.setText("PRODUCTOS");

        Combo_TProducto.setBackground(new java.awt.Color(51, 51, 51));
        Combo_TProducto.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        Combo_TProducto.setForeground(new java.awt.Color(255, 255, 255));
        Combo_TProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Maquillaje", "Productos de Belleza" }));
        Combo_TProducto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Combo_TProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Combo_TProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Combo_TProductoActionPerformed(evt);
            }
        });

        Label_Color.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        Label_Color.setForeground(new java.awt.Color(0, 0, 0));
        Label_Color.setText("Color");

        Combo_Color.setBackground(new java.awt.Color(51, 51, 51));
        Combo_Color.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        Combo_Color.setForeground(new java.awt.Color(255, 255, 255));
        Combo_Color.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Rojo", "Rosa", "Morado", "Fucsia", "Dorado", "Plateado", "Blanco", "Vinotino" }));
        Combo_Color.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Combo_Color.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        Label_Tproducto.setBackground(new java.awt.Color(51, 0, 153));
        Label_Tproducto.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        Label_Tproducto.setForeground(new java.awt.Color(0, 0, 0));
        Label_Tproducto.setText("Tipo de Producto");

        Label_Género.setBackground(new java.awt.Color(0, 0, 0));
        Label_Género.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        Label_Género.setForeground(new java.awt.Color(0, 0, 0));
        Label_Género.setText("Género");

        Radio_Masculino.setBackground(new java.awt.Color(51, 51, 51));
        Radio_Masculino.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        Radio_Masculino.setForeground(new java.awt.Color(0, 0, 0));
        Radio_Masculino.setText("Masculino");
        Radio_Masculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Radio_MasculinoActionPerformed(evt);
            }
        });

        Radio_Femenino.setBackground(new java.awt.Color(51, 51, 51));
        Radio_Femenino.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        Radio_Femenino.setForeground(new java.awt.Color(0, 0, 0));
        Radio_Femenino.setText("Femenino");
        Radio_Femenino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Radio_FemeninoActionPerformed(evt);
            }
        });

        Label_Tono.setBackground(new java.awt.Color(51, 0, 153));
        Label_Tono.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        Label_Tono.setForeground(new java.awt.Color(0, 0, 0));
        Label_Tono.setText("Tono");

        Combo_Tono.setBackground(new java.awt.Color(51, 51, 51));
        Combo_Tono.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        Combo_Tono.setForeground(new java.awt.Color(255, 255, 255));
        Combo_Tono.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Claro", "Oscuro" }));
        Combo_Tono.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Combo_Tono.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Combo_Tono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Combo_TonoActionPerformed(evt);
            }
        });

        Label_Producto.setBackground(new java.awt.Color(51, 0, 153));
        Label_Producto.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        Label_Producto.setForeground(new java.awt.Color(0, 0, 0));
        Label_Producto.setText("Producto");

        Combo_Producto.setBackground(new java.awt.Color(51, 51, 51));
        Combo_Producto.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        Combo_Producto.setForeground(new java.awt.Color(255, 255, 255));
        Combo_Producto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Labial", "Pestañina", "Esmalte", "Polvo Compacto" }));
        Combo_Producto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Combo_Producto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Combo_Producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Combo_ProductoActionPerformed(evt);
            }
        });

        Label_Cantidad.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        Label_Cantidad.setForeground(new java.awt.Color(0, 0, 0));
        Label_Cantidad.setText("Cantidad");

        Text_Cantidad.setBackground(new java.awt.Color(34, 34, 34));
        Text_Cantidad.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        Text_Cantidad.setForeground(new java.awt.Color(255, 255, 255));

        Text_Peso.setBackground(new java.awt.Color(34, 34, 34));
        Text_Peso.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        Text_Peso.setForeground(new java.awt.Color(255, 255, 255));

        Label_Peso.setBackground(new java.awt.Color(51, 0, 153));
        Label_Peso.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        Label_Peso.setForeground(new java.awt.Color(0, 0, 0));
        Label_Peso.setText("Peso");
        Label_Peso.setMaximumSize(new java.awt.Dimension(20, 19));

        Combo_Marca.setBackground(new java.awt.Color(51, 51, 51));
        Combo_Marca.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        Combo_Marca.setForeground(new java.awt.Color(255, 255, 255));
        Combo_Marca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Esika", "Yanbal", "Vogue", "Avon" }));
        Combo_Marca.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Combo_Marca.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Combo_Marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Combo_MarcaActionPerformed(evt);
            }
        });

        Label_Marca.setBackground(new java.awt.Color(0, 0, 0));
        Label_Marca.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        Label_Marca.setForeground(new java.awt.Color(0, 0, 0));
        Label_Marca.setText("Marca");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Label_Productos)
                            .addGap(31, 31, 31))
                        .addComponent(jSeparator1)
                        .addComponent(jSeparator2)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Label_Género)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(133, 133, 133)
                                    .addComponent(Radio_Masculino, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(Radio_Femenino))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Label_Producto)
                                        .addComponent(Label_Marca))
                                    .addGap(82, 82, 82)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Combo_Marca, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Combo_Producto, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(82, 82, 82)
                            .addComponent(Label_Color)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Label_Tproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(12, 12, 12)
                            .addComponent(Combo_TProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 217, Short.MAX_VALUE)
                            .addComponent(Combo_Color, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jSeparator3)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(Label_Peso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(71, 71, 71)
                                    .addComponent(Text_Peso, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Label_Cantidad)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(104, 104, 104)
                                        .addComponent(Text_Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(Label_Tono)
                                    .addGap(64, 64, 64)
                                    .addComponent(Combo_Tono, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 357, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Label_Productos)
                    .addGap(57, 57, 57)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Combo_Color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Label_Color)
                        .addComponent(Combo_TProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Label_Tproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(28, 28, 28)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Label_Género)
                        .addComponent(Radio_Masculino)
                        .addComponent(Radio_Femenino)
                        .addComponent(Label_Tono)
                        .addComponent(Combo_Tono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(24, 24, 24)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Combo_Producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Label_Producto))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Label_Cantidad)
                            .addComponent(Text_Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(10, 10, 10)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(8, 8, 8)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Label_Marca)
                        .addComponent(Combo_Marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Label_Peso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Text_Peso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Combo_TProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Combo_TProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Combo_TProductoActionPerformed

    private void Radio_MasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Radio_MasculinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Radio_MasculinoActionPerformed

    private void Radio_FemeninoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Radio_FemeninoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Radio_FemeninoActionPerformed

    private void Combo_TonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Combo_TonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Combo_TonoActionPerformed

    private void Combo_ProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Combo_ProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Combo_ProductoActionPerformed

    private void Combo_MarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Combo_MarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Combo_MarcaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Combo_Color;
    private javax.swing.JComboBox<String> Combo_Marca;
    private javax.swing.JComboBox<String> Combo_Producto;
    private javax.swing.JComboBox<String> Combo_TProducto;
    private javax.swing.JComboBox<String> Combo_Tono;
    private javax.swing.JLabel Label_Cantidad;
    private javax.swing.JLabel Label_Color;
    private javax.swing.JLabel Label_Género;
    private javax.swing.JLabel Label_Marca;
    private javax.swing.JLabel Label_Peso;
    private javax.swing.JLabel Label_Producto;
    private javax.swing.JLabel Label_Productos;
    private javax.swing.JLabel Label_Tono;
    private javax.swing.JLabel Label_Tproducto;
    private javax.swing.JRadioButton Radio_Femenino;
    private javax.swing.JRadioButton Radio_Masculino;
    private javax.swing.JTextField Text_Cantidad;
    private javax.swing.JTextField Text_Peso;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
